version: '2'
services:
  sgl-mysql:
    container_name: sgl-mysql
    image: mysql:latest
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sgl
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=0 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
